# Generated by Django 3.0.6 on 2020-05-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0002_userconnection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userconnection',
            unique_together={('follows_user', 'followed_user')},
        ),
    ]
